image: ubuntu:20.04

stages:
 - format
 - build

before_script:
 - apt-get update -qq
 - export DEBIAN_FRONTEND=noninteractive && apt-get install -y -qq 
    casacore-data casacore-dev 
    cmake
    g++
    git 
    libblas-dev liblapack-dev 
    libboost-filesystem-dev libboost-system-dev libboost-date-time-dev 
    libboost-program-options-dev libboost-test-dev 
    libcfitsio-dev 
    libfftw3-dev 
    libgsl-dev 
    libhdf5-dev
    libpython3-dev 
    pkg-config
    pybind11-dev
    python3-dev python3-numpy

format:
  stage: format
  script:
    - apt-get -y install python3-pip
    - pip3 install clang-format
    # clang-format should be version 9
    - clang-format -version
    - ./scripts/clang-format-check.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make
    - make install
    - make check

